# Generated by Django 3.2.6 on 2023-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230425_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USR', 'user'), ('ADM', 'admin')], default='USR', max_length=5),
        ),
    ]
